import type { MovieData } from '@/types/movies';
import type { RawMovieData, RawMovieCreditsData } from '@/types/moviesApi';

export const rawMovieDetailsData: RawMovieData = {
	adult: false,
	backdrop_path: '/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg',
	belongs_to_collection: null,
	budget: 40000000,
	genres: [
		{
			id: 28,
			name: 'Action',
		},
		{
			id: 80,
			name: 'Crime',
		},
		{
			id: 53,
			name: 'Thriller',
		},
	],
	homepage: 'https://www.amazon.com/salp/aworkingman?hhf',
	id: 1197306,
	imdb_id: 'tt9150192',
	origin_country: ['GB', 'US'],
	original_language: 'en',
	original_title: 'A Working Man',
	overview:
		"Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
	popularity: 721.9495,
	poster_path: '/xUkUZ8eOnrOnnJAfusZUqKYZiDu.jpg',
	production_companies: [
		{
			id: 118475,
			logo_path: '/x8mwqWGZK2gQvrp5QlYQho1VgXj.png',
			name: 'Cedar Park Entertainment',
			origin_country: 'US',
		},
		{
			id: 219295,
			logo_path: null,
			name: 'BlockFilm',
			origin_country: 'US',
		},
		{
			id: 218150,
			logo_path: null,
			name: 'Punch Palace Productions',
			origin_country: 'GB',
		},
		{
			id: 166120,
			logo_path: '/fRuHQF9DB4Zl3ha62D5Bpu1a5TL.png',
			name: 'Balboa Productions',
			origin_country: 'US',
		},
		{
			id: 22146,
			logo_path: '/v37N1mFeXNQfvPankg3feBhVvM7.png',
			name: 'Black Bear Pictures',
			origin_country: 'US',
		},
		{
			id: 181874,
			logo_path: '/crrgXvLhDO9c57HYrbO4H58Vxmb.png',
			name: 'Fifth Season',
			origin_country: 'US',
		},
		{
			id: 253169,
			logo_path: null,
			name: 'CAT5',
			origin_country: 'US',
		},
	],
	production_countries: [
		{
			iso_3166_1: 'GB',
			name: 'United Kingdom',
		},
		{
			iso_3166_1: 'US',
			name: 'United States of America',
		},
	],
	release_date: '2025-03-26',
	revenue: 86925155,
	runtime: 116,
	spoken_languages: [
		{
			english_name: 'English',
			iso_639_1: 'en',
			name: 'English',
		},
		{
			english_name: 'Russian',
			iso_639_1: 'ru',
			name: 'Pусский',
		},
		{
			english_name: 'Spanish',
			iso_639_1: 'es',
			name: 'Español',
		},
	],
	status: 'Released',
	tagline: 'Human traffickers beware.',
	title: 'A Working Man',
	video: false,
	vote_average: 6.3,
	vote_count: 445,
};
export const rawMovieCreditsData: RawMovieCreditsData = {
	id: 1197306,
	cast: [
		{
			adult: false,
			gender: 2,
			id: 976,
			known_for_department: 'Acting',
			name: 'Jason Statham',
			original_name: 'Jason Statham',
			popularity: 28.7119,
			profile_path: '/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg',
			cast_id: 7,
			character: 'Levon Cade',
			credit_id: '653c591c519bbb00fe5be666',
			order: 0,
		},
		{
			adult: false,
			gender: 2,
			id: 35029,
			known_for_department: 'Acting',
			name: 'David Harbour',
			original_name: 'David Harbour',
			popularity: 3.1411,
			profile_path: '/tCbxqq6NUWVNoybztPsMwmJqwdI.jpg',
			cast_id: 8,
			character: 'Gunny Lefferty',
			credit_id: '6614b3423d7454016207b746',
			order: 1,
		},
		{
			adult: false,
			gender: 2,
			id: 454,
			known_for_department: 'Acting',
			name: 'Michael Peña',
			original_name: 'Michael Peña',
			popularity: 2.6344,
			profile_path: '/ft9e3EX4JG9MwK9pXwgbJ8ZvFoV.jpg',
			cast_id: 9,
			character: 'Joe Garcia',
			credit_id: '6614b3476c84920185fdcc3a',
			order: 2,
		},
		{
			adult: false,
			gender: 2,
			id: 973,
			known_for_department: 'Acting',
			name: 'Jason Flemyng',
			original_name: 'Jason Flemyng',
			popularity: 2.2254,
			profile_path: '/nYl0180ACnLzVlGbaAfuPtdGr9K.jpg',
			cast_id: 10,
			character: 'Wolo Kolisnyk',
			credit_id: '6614b34e048638017c1bb251',
			order: 3,
		},
		{
			adult: false,
			gender: 1,
			id: 3953574,
			known_for_department: 'Acting',
			name: 'Arianna Rivas',
			original_name: 'Arianna Rivas',
			popularity: 6.3245,
			profile_path: '/a4dRvxh2csK8pnMVz5Xrh8MrE8X.jpg',
			cast_id: 11,
			character: 'Jenny Garcia',
			credit_id: '6614b35659008601857ebf27',
			order: 4,
		},
		{
			adult: false,
			gender: 1,
			id: 1862014,
			known_for_department: 'Acting',
			name: 'Noemi Gonzalez',
			original_name: 'Noemi Gonzalez',
			popularity: 0.7842,
			profile_path: '/ljWB8Hkw6KMeyiT1gNrBcK4OsJZ.jpg',
			cast_id: 13,
			character: 'Carla Garcia',
			credit_id: '6614b3a89408ec017d2c42e9',
			order: 5,
		},
		{
			adult: false,
			gender: 2,
			id: 1111204,
			known_for_department: 'Acting',
			name: 'Emmett Scanlan',
			original_name: 'Emmett Scanlan',
			popularity: 1.0134,
			profile_path: '/1NmZuOXJ9XXLU5Yez5iedoEZWRp.jpg',
			cast_id: 14,
			character: 'Viper',
			credit_id: '6614b3ad15a4a1017df81c0d',
			order: 6,
		},
		{
			adult: false,
			gender: 1,
			id: 147382,
			known_for_department: 'Acting',
			name: 'Eve Mauro',
			original_name: 'Eve Mauro',
			popularity: 1.4218,
			profile_path: '/jaY2RiuWQsS2w7wtRKbtBZOBzEn.jpg',
			cast_id: 15,
			character: 'Artemis',
			credit_id: '6614b3b5ac617c0164b14a24',
			order: 7,
		},
		{
			adult: false,
			gender: 2,
			id: 1011106,
			known_for_department: 'Acting',
			name: 'Maximilian Osinski',
			original_name: 'Maximilian Osinski',
			popularity: 0.7721,
			profile_path: '/wMRtFsZSR9FvYj1wzsziKQqpZ0C.jpg',
			cast_id: 16,
			character: 'Dimi Kolisnyk',
			credit_id: '6614b3ba9408ec017d2c4311',
			order: 8,
		},
		{
			adult: false,
			gender: 1,
			id: 4642648,
			known_for_department: 'Acting',
			name: 'Kristina Poli',
			original_name: 'Kristina Poli',
			popularity: 0.0847,
			profile_path: '/8IiB1luhX2rViBKbALrr8QXaY2X.jpg',
			cast_id: 17,
			character: 'Svetlana Kolisnyk',
			credit_id: '6614b3df6c84920185fdcd29',
			order: 9,
		},
		{
			adult: false,
			gender: 2,
			id: 1327564,
			known_for_department: 'Acting',
			name: 'Andrej Kaminsky',
			original_name: 'Andrej Kaminsky',
			popularity: 1.7411,
			profile_path: '/xxMY0ZBXqQWe5BbwucYyVCS9P7Y.jpg',
			cast_id: 18,
			character: 'Symon Kharchenko',
			credit_id: '6614b3e55437f501647e024e',
			order: 10,
		},
	],
	crew: [
		{
			adult: false,
			gender: 2,
			id: 19769,
			known_for_department: 'Directing',
			name: 'David Ayer',
			original_name: 'David Ayer',
			popularity: 1.3893,
			profile_path: '/7JmWK2wg2StEc9eYjY96s7OJgb7.jpg',
			credit_id: '653c576e719aeb00ab2af19b',
			department: 'Directing',
			job: 'Director',
		},
		{
			adult: false,
			gender: 2,
			id: 19769,
			known_for_department: 'Directing',
			name: 'David Ayer',
			original_name: 'David Ayer',
			popularity: 1.3893,
			profile_path: '/7JmWK2wg2StEc9eYjY96s7OJgb7.jpg',
			credit_id: '653c5777c8a5ac00e3a09806',
			department: 'Production',
			job: 'Producer',
		},
		{
			adult: false,
			gender: 2,
			id: 16483,
			known_for_department: 'Acting',
			name: 'Sylvester Stallone',
			original_name: 'Sylvester Stallone',
			popularity: 9.1791,
			profile_path: '/gn3pDWthJqR0VDYGViGD3048og7.jpg',
			credit_id: '653c577fc8a5ac00ad36b159',
			department: 'Writing',
			job: 'Screenplay',
		},
		{
			adult: false,
			gender: 2,
			id: 16483,
			known_for_department: 'Acting',
			name: 'Sylvester Stallone',
			original_name: 'Sylvester Stallone',
			popularity: 9.1791,
			profile_path: '/gn3pDWthJqR0VDYGViGD3048og7.jpg',
			credit_id: '653c578be894a600ad564466',
			department: 'Production',
			job: 'Producer',
		},
	],
};
export const expectedMovieData: MovieData = {
	id: 1197306,
	title: 'A Working Man',
	releaseDate: '2025',
	img: 'https://image.tmdb.org/t/p/w500/xUkUZ8eOnrOnnJAfusZUqKYZiDu.jpg',
	originalTitle: 'A Working Man',
	description:
		"Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
	director: 'David Ayer',
	genres: ['Action', 'Crime', 'Thriller'],
	rating: 6.3,
	voteCount: 445,
	cast: [
		{
			id: 976,
			name: 'Jason Statham',
			character: 'Levon Cade',
			img: 'https://image.tmdb.org/t/p/w500/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg',
		},
		{
			id: 35029,
			name: 'David Harbour',
			character: 'Gunny Lefferty',
			img: 'https://image.tmdb.org/t/p/w500/tCbxqq6NUWVNoybztPsMwmJqwdI.jpg',
		},
		{
			id: 454,
			name: 'Michael Peña',
			character: 'Joe Garcia',
			img: 'https://image.tmdb.org/t/p/w500/ft9e3EX4JG9MwK9pXwgbJ8ZvFoV.jpg',
		},
		{
			id: 973,
			name: 'Jason Flemyng',
			character: 'Wolo Kolisnyk',
			img: 'https://image.tmdb.org/t/p/w500/nYl0180ACnLzVlGbaAfuPtdGr9K.jpg',
		},
		{
			id: 3953574,
			name: 'Arianna Rivas',
			character: 'Jenny Garcia',
			img: 'https://image.tmdb.org/t/p/w500/a4dRvxh2csK8pnMVz5Xrh8MrE8X.jpg',
		},
		{
			id: 1862014,
			name: 'Noemi Gonzalez',
			character: 'Carla Garcia',
			img: 'https://image.tmdb.org/t/p/w500/ljWB8Hkw6KMeyiT1gNrBcK4OsJZ.jpg',
		},
		{
			id: 1111204,
			name: 'Emmett Scanlan',
			character: 'Viper',
			img: 'https://image.tmdb.org/t/p/w500/1NmZuOXJ9XXLU5Yez5iedoEZWRp.jpg',
		},
		{
			id: 147382,
			name: 'Eve Mauro',
			character: 'Artemis',
			img: 'https://image.tmdb.org/t/p/w500/jaY2RiuWQsS2w7wtRKbtBZOBzEn.jpg',
		},
		{
			id: 1011106,
			name: 'Maximilian Osinski',
			character: 'Dimi Kolisnyk',
			img: 'https://image.tmdb.org/t/p/w500/wMRtFsZSR9FvYj1wzsziKQqpZ0C.jpg',
		},
	],
};
